import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";


import localFont from "next/font/local";

const modernNegra = localFont({
 src: "../public/fonts/Modern-Negra-Demo.ttf", // relative path
  variable: "--font-modern-negra",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={modernNegra.variable}
      >
        <main className="p-4">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
